### ISSUE TITLE
Is possible to add RAW data in the message?

### ISSUE THREAD

**Issue by bobboteck** [rbonghi/ros_jetson_stats#1]
Hi @rbonghi, I want ask you if is possible to add at RAM message information the RAW data of use.
Follow the reference in your code:

https://github.com/rbonghi/ros_jetson_stats/blob/48840f372825916404d58cb211724f2df8569296/src/utils.py#L191-L196

**Comment by rbonghi** [comment]
I'm thinking to add an extra field for all key values where is show the Unit.

**Comment by rbonghi** [comment]
Update all key values with this new output:

* Use (RAW)
* Total (RAW)
* Unit

No changes for **Message** field and extra fields

![image](https://user-images.githubusercontent.com/4551246/81505946-e3cbac80-92ea-11ea-9cf6-e5b3e8723fa3.png)
